//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlosarioCorreos.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GlosarioCorreos.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Buscar_90 {
            get {
                object obj = ResourceManager.GetObject("Buscar_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap file_search_b_w {
            get {
                object obj = ResourceManager.GetObject("file_search b&w", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gears_animated_t {
            get {
                object obj = ResourceManager.GetObject("gears_animated_t", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Glossary_write_128 {
            get {
                object obj = ResourceManager.GetObject("Glossary write_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mail_Add_27 {
            get {
                object obj = ResourceManager.GetObject("Mail_Add_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Mail_Min_27 {
            get {
                object obj = ResourceManager.GetObject("Mail_Min_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause_27 {
            get {
                object obj = ResourceManager.GetObject("pause_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play_27 {
            get {
                object obj = ResourceManager.GetObject("play_27", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET LANGUAGE SPANISH
        ///
        ///SELECT GC_Remitente AS Remitente
        ///	,convert(VARCHAR, GC_Fecha, 103) + &apos; &apos; + convert(VARCHAR, GC_Fecha, 108) AS Fecha
        ///	,GC_Asunto AS Asunto
        ///	,C.GC_Id AS ID
        ///	,GC_Cuerpo AS Correo
        ///FROM GlosarioCorreos C
        ///.
        /// </summary>
        internal static string QueryBaseBusqueda {
            get {
                return ResourceManager.GetString("QueryBaseBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @Destinatario VARCHAR(150)
        ///DECLARE @Destinatarios VARCHAR(4000)
        ///
        ///SET @Destinatarios = &apos;&apos;
        ///
        ///DECLARE cursorBloq CURSOR FAST_FORWARD FOR
        ///  SELECT DISTINCT GCD_Destinatario
        ///  FROM   GlosarioCorreos_Destinatarios
        ///  WHERE GC_Id = @@GC_Id
        ///  ORDER  BY 1
        ///  FOR READ ONLY
        ///
        ///OPEN cursorBloq
        ///
        ///FETCH NEXT FROM cursorBloq INTO @Destinatario
        ///
        ///WHILE @@FETCH_STATUS = 0
        ///  BEGIN
        ///      SET @Destinatarios = @Destinatarios + @Destinatario + &apos;; &apos;
        ///
        ///      FETCH NEXT FROM cursorBloq INTO @Destinatario
        ///  END        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryInfoCorreo {
            get {
                return ResourceManager.GetString("QueryInfoCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_mail_90 {
            get {
                object obj = ResourceManager.GetObject("save_mail_90", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
